version: '3.9'

services:
  mongo-db:
    container_name: db-container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DB_connection_string:   'mongodb://mongo_db/buchi'
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}


    