version: '3'

services:
  app:
    container_name: app
    restart: always
    build: .
    ports: 
      - '5000:5000'
    links:
      - mongo
    networks:
      - buchi_network

  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo:latest
    volumes:
      - ./dbdata:<absolute-path-to-local-storage>
    networks:
      - buchi_network

networks:
  buchi_network:
    driver: bridge
